App\Entity\User:
  attributes:
    id:
      groups: [user_read]
    name:
      groups: [user_read, user_register, user_update]
    email:
      groups: [user_read, user_register]
    password:
      groups: [user_register, user_update]
    roles:
      groups: [user_read, user_register, user_update]
